import { postReview } from "../services/reviewService";
import Review from "../models/Review";
import { ObjectId } from "mongodb";

export interface ReviewPayload {
    item_oid: string;
    user: string;
    content: string;
    date: string;
    time: string;
    uid: string;
}

export async function postReviewJob(reviewPayload: ReviewPayload): Promise<Review> {
    // Create Review object from payload
    const review = new Review(
        undefined, // _id will be generated by MongoDB
        new ObjectId(reviewPayload.item_oid),
        reviewPayload.user,
        reviewPayload.content,
        reviewPayload.date,
        reviewPayload.time,
        reviewPayload.uid
    );

    // Post the review
    const postedReview = await postReview(review);
    
    return postedReview;
}
